#!/usr/bin/env node
import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { configDir, ensureDir } from "../src/config/paths.ts"

/**
 * Installs the agent and tools into the user's personal OpenCode configuration.
 *
 * Deliberately conservative:
 *  - It never edits opencode.json. Agents and tools are file-based, so no
 *    merge into the user's existing config is required.
 *  - It backs up any file it would overwrite.
 *  - It writes a re-export shim rather than copying the tool, so imports keep
 *    resolving against this repository's node_modules.
 */

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")

function opencodeConfigDir(): string {
  const xdg = process.env.XDG_CONFIG_HOME
  const base = xdg && xdg.trim().length ? xdg : path.join(os.homedir(), ".config")
  return path.join(base, "opencode")
}

function backupIfPresent(file: string): string | null {
  if (!fs.existsSync(file)) return null
  const stamp = new Date().toISOString().replace(/[:.]/g, "-")
  const backup = `${file}.backup-${stamp}`
  fs.copyFileSync(file, backup)
  return backup
}

function writeFile(target: string, contents: string): void {
  ensureDir(path.dirname(target))
  const backup = backupIfPresent(target)
  fs.writeFileSync(target, contents)
  console.log(`  wrote ${target}${backup ? ` (backed up existing to ${path.basename(backup)})` : ""}`)
}

function main(): void {
  const ocDir = opencodeConfigDir()
  console.log(`Installing into ${ocDir}`)

  const agentSource = path.join(repoRoot, "opencode", "agents", "daily-tasks.md")
  writeFile(path.join(ocDir, "agents", "daily-tasks.md"), fs.readFileSync(agentSource, "utf8"))

  const toolPath = path.join(repoRoot, "opencode", "tools", "desk.ts")
  const shim = `// Generated by zoho-auto-tasks. Re-exports the tools from the repository so that
// imports resolve against ${repoRoot}/node_modules.
export * from ${JSON.stringify(toolPath)}
`
  writeFile(path.join(ocDir, "tools", "desk.ts"), shim)

  const envTarget = path.join(configDir(), ".env")
  if (!fs.existsSync(envTarget)) {
    ensureDir(configDir())
    fs.copyFileSync(path.join(repoRoot, ".env.example"), envTarget)
    fs.chmodSync(envTarget, 0o600)
    console.log(`  created ${envTarget} from the example template`)
  } else {
    console.log(`  kept existing ${envTarget}`)
  }

  console.log(`
Installed. Tools will load as desk_get_context, desk_prepare_batch, desk_submit_batch,
desk_get_batch, desk_reconcile_batch and desk_confirm_distinct, and the agent appears as
"daily-tasks".

Next:
  1. Fill in ${envTarget} with your Zoho credentials, owner email and department.
  2. Run:  npm run setup                 (read-only discovery, then writes derived IDs)
  3. Run:  node src/cli.ts doctor
`)
}

main()
